export interface StringUnit {
  state: string;
  value: string;
}

export interface LocalizationEntry {
  stringUnit: StringUnit;
}

export interface StringEntry {
  comment?: string;
  extractionState?: string;
  isCommentAutoGenerated?: boolean;
  shouldTranslate?: boolean;
  localizations?: Record<string, LocalizationEntry>;
}

export interface XCStringCatalog {
  sourceLanguage?: string;
  strings: Record<string, StringEntry>;
  version?: string;
}

export interface ExportTranslatableOptions {
  xcstringsPath: string;
  outCsvPath: string;
  onlyMissingLocale?: string;
  keyRegex?: RegExp;
  chunkSize?: number;
}

export interface ExportTranslatableResult {
  count: number;
  writtenCsvPaths: string[];
}

export interface TranslationRow {
  key: string;
  locale: string;
  value: string;
}

export interface ApplyTranslationsOptions {
  xcstringsPath: string;
  translationsCsvPath: string;
  outXcstringsPath?: string;
  strictKeys?: boolean;
  onlyIfMissingForTargetLocale?: boolean;
}

export interface ApplyTranslationsResult {
  updated: number;
  skippedMissingKey: string[];
  skippedAlreadyTranslated: string[];
  warnings: string[];
}

export interface AutoFillMissingLocaleFromLocaleOptions {
  xcstringsPath: string;
  sourceLocale: string;
  targetLocale: string;
  transform: (sourceText: string) => string;
  outXcstringsPath?: string;
}

export interface AutoFillMissingLocaleFromLocaleResult {
  updated: number;
  skippedMissingSource: number;
  skippedAlreadyTranslated: number;
  skippedNotTranslatable: number;
}
